### ISSUE TITLE
Create xsdk compatibility template and example

### ISSUE THREAD

**Issue by maherou** [xsdk-project/xsdk-policy-compatibility#1]
We want a template that lists the xSDK community policies and has space for describing how a package complies with a given policy.

The initial draft of the policy is in this repo:

https://github.com/xsdk-project/xsdk-policy-compatibility

**Comment by maherou** [comment]
I am wondering if we can use the GitHub checklist format and a table for this template.  The current hypre example is very wordy and long, mostly with statements that "hypre is compliant".  I can provide an example, if that seems reasonable.

**Comment by curfman** [comment]
Yes, please provide an example of what you have in mind.

**Comment by maherou** [comment]
I have created a new format for the template.  See:

https://github.com/xsdk-project/xsdk-policy-compatibility/blob/master/template_v2.md

@ulrikeyang, please look to see if this is useful.

**Comment by bartlettroscoe** [comment]
Template looks fine. The only problem is what this will look like if one wants to expand on the explanation in "Notes".  For example, we discussed needing a longer explanation for when a required policy is not met but there is a workaround or other mitigation available that might allow the package to still be included in the xSDK set of packages.  Such an explanation will not easily fit in a table cell.

Could there be a "see below" link inside of the "Notes" field to expanded text below when needed?   Many forms allow for this type of expanded text in later pages.

**Comment by ulrikeyang** [comment]
We could go back to the original template I suggested where you have plenty of space to enter any of these comments, which was the original intention.
The table format is good if you want something like a checklist, however my understanding was that we wanted more, including examples, workarounds etc that would be helpful for future xSDK members.
The problem with a see below link is that this moves the comments away from the actual policy and can become confusing when there are several of those.
I guess we can discuss all this at the meeting today. There might be no perfect solution.

Cheers
Ulrike

**Comment by maherou** [comment]
The explanations are the most important part of the compliance document, so we should make sure these are supported well by the format.  The first format seemed too verbose, especially when most of the answers are brief, but the second is too compact.  If there is an obvious hybrid, that is fine with me.  Otherwise, going back to the first template is OK.

**Comment by bartlettroscoe** [comment]
What is nice about a table is that you get a quick overview of how will a given code is doing and satisfying the various policies without having to wade through pages and pages of detail.  With the hybrid approach (a summary table with optional extended explanations linked to below), you get both a quick summary view and can see more detail if you want.

**Comment by maherou** [comment]
Hybrid is fine with me. Hybrid also combines all the explanations compactly.

On Sep 7, 2017, at 9:08 AM, Roscoe A. Bartlett <notifications@github.com<mailto:notifications@github.com>> wrote:


What is nice about a table is that you get a quick overview of how will a given code is doing and satisfying the various policies without having to wade through pages and pages of detail. With the hybrid approach (a summary table with optional extended explanations linked to below), you get both a quick summary view and can see more detail if you want.

-

**Comment by ulrikeyang** [comment]
What I don’t like about the suggested hybrid is the link below part, which moves the comments away from the text. I agree that having a compact table that tells us at one glance the overall status is good.

How about including a table, which only uses the policy numbers on the left (and links to the fuller text below) and the status and short comments and links, but keeping the verbose portions below together with the long comments? That way you get your quick overview right away in an even shorter form

**Comment by maherou** [comment]
I like the modified V2 that Jim created.  What do others think?

**Comment by bartlettroscoe** [comment]
> I like the modified V2 that Jim created. What do others think?

The updated version is shown here:

* https://github.com/xsdk-project/xsdk-policy-compatibility/blob/952f8162cd7003af99ef4ac3ffab039fffeefbef/template_v2.md

It looks okay except the longer explanations need to come after both tables, not in between them.

Also, it needs short instructions (separate document) on how to add longer explanations.

**Comment by ulrikeyang** [comment]
I agree with Ross that the longer explanations need to come after the two tables, otherwise – in case of a very long explanation – you will have to search for the second table.
Regarding the instructions, we could include them in the form.
Ulrike

**Comment by maherou** [comment]
It seems that we have finished this task.  I think the PETSc version is a very good example of how to complete the template, and suggest that people start with its text as a reference or starting point.

I am closing this issue.
