### ISSUE TITLE
Out of date compatibility documents

### ISSUE THREAD

**Issue by balos1** [xsdk-project/xsdk-policy-compatibility#39]
The compatibility documents for the following packages are out of date and need to be updated:

- [x] dealii @bangerth 
- [x] dtk @dalg24
- [x] heffte @mkstoyanov @stomov 
- [x] magma @stomov
- [x] mfem @v-dobrev 
- [x] omega-h @cwsmith 
- [x] petsc @balay 
- [x] plasma @luszczek 
- [x] precice @fsimonis 
- [x] pumi @cwsmith 
- [x] slepc @joseeroman @luszczek 
- [x] trilinos @keitat @jwillenbring 

We would like to have these updated as soon as possible. The template can be used to see what needs to be updated. Please update and open a pull request.

**Comment by aprokop** [comment]
@balos1 Does "out of date" mean that we simply need to move the text to the latest template version?
