### ISSUE TITLE
Update compatibility template.

### ISSUE THREAD

**Issue by balos1** [xsdk-project/xsdk-policy-compatibility#8]
The compatibility template will need to be updated to include the new R6 policy that will be introduced in v0.4.0.

> R6: Each package should document the versions of packages with which it can work or upon which it depends, including software external to the xSDK, preferably in a machine-readable form. The developers of xSDK member packages will coordinate the needed versions of various packages for each xSDK release.

In addition, in the template M3 only covers the requirement that a user-provided MPI communicator is supported. It does not reference the other parts of M3 which have to do with MPI 2/3 feature/version detection, and MPI error handling.

> M3. Each xSDK-compatible package that utilizes MPI must restrict its MPI operations to MPI communicators that are provided to it and not use directly MPI_COMM_WORLD. The package should use configure tests or version tests to detect MPI 2 or MPI 3 features that may not be available; it should not be assumed that a full MPI 2 or MPI 3 implementation is available. The package can change the MPI error-handling mode by default but should have an option to prevent it from changing the MPI error handling (which may have been set by another package or the application). The package should also behave appropriately regardless of the MPI error handling being used. There is no requirement that the package provide a sequential (non-MPI) version, although this functionality is welcome, too. If the package provides a sequential version, there is no requirement that it be compatible or usable with other xSDK-compatible packages running without MPI.

**Comment by curfman** [comment]
Cody -- Thanks for mentioning this.  Please update the template as needed to reflect new policies.

**Comment by balos1** [comment]
Template has been updated to reflect the new policies.
